name: Deploy to AWS Amplify

on:
  push:
    branches:
      - main  

permissions:
  contents: read

env:
  AWS_REGION: eu-west-2
  AMPLIFY_APP_ID: ${{ secrets.AMPLIFY_APP_ID }}
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
   deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }} 

      - name: Trigger Amplify deployment
        run: |
          echo "App ID: ${{ env.AMPLIFY_APP_ID }}"
          echo "Region: ${{ env.AWS_REGION }}"
          aws amplify list-apps --region ${{ env.AWS_REGION }}
          aws amplify start-job \
            --app-id ${{ env.AMPLIFY_APP_ID }} \
            --branch-name main \
            --job-type RELEASE

      - name: Confirm deployment status
        run: echo "Deployment triggered successfully on AWS Amplify"